name: COBOL Check Automation

on:
  push:
    branches: [ master ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: temurin
    - name: Install zowe
      run: |
        npm install -g @zowe/cli@zowe-v2-lts
        zowe profiles create zosmf-profile myprofile123 --host 204.90.115.200 --port 10443 --user ${ZOWE_USERNAME} --password ${ZOWE_PASSWORD}
    - name: Run COBOL Check
      env:
        ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
      run: |
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
        
